import os, json, base64, time, re, urllib.request

TOKEN = os.environ.get('GITHUB_TOKEN','')
REPO = 'gulrajb/vitalpicks'

# ── Curated Picsum IDs by topic (manually selected for relevance) ──────────────
# These are real photos from picsum.photos that match each topic
TOPIC_IMAGES = {
    # Supplements
    'protein':     'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&q=80&auto=format&fit=crop',
    'creatine':    'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80&auto=format&fit=crop',
    'preworkout':  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80&auto=format&fit=crop',
    'multivit':    'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80&auto=format&fit=crop',
    'omega3':      'https://images.unsplash.com/photo-1614350292382-c448d0110dfa?w=800&q=80&auto=format&fit=crop',
    'vitd':        'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80&auto=format&fit=crop',
    'magnesium':   'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80&auto=format&fit=crop',
    'probiotics':  'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80&auto=format&fit=crop',
    'collagen':    'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80&auto=format&fit=crop',
    'sleep':       'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&q=80&auto=format&fit=crop',
    'ashwagandha': 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80&auto=format&fit=crop',
    'greens':      'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&q=80&auto=format&fit=crop',
    'nootropics':  'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&q=80&auto=format&fit=crop',
    # Fitness
    'yoga':        'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80&auto=format&fit=crop',
    'dumbbells':   'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80&auto=format&fit=crop',
    'kettlebell':  'https://images.unsplash.com/photo-1517963879433-6ad2a56fcd82?w=800&q=80&auto=format&fit=crop',
    'resistance':  'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&q=80&auto=format&fit=crop',
    'treadmill':   'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&q=80&auto=format&fit=crop',
    'pullup':      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80&auto=format&fit=crop',
    'rowing':      'https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=800&q=80&auto=format&fit=crop',
    'massage':     'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80&auto=format&fit=crop',
    'foam':        'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80&auto=format&fit=crop',
    'homegym':     'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80&auto=format&fit=crop',
    'squat':       'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=800&q=80&auto=format&fit=crop',
    'bench':       'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?w=800&q=80&auto=format&fit=crop',
    'running':     'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&q=80&auto=format&fit=crop',
    'tracker':     'https://images.unsplash.com/photo-1575377427642-087cf684ad4b?w=800&q=80&auto=format&fit=crop',
    'gym_general': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80&auto=format&fit=crop',
    'health':      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80&auto=format&fit=crop',
}

# Map article filenames to image URLs
ARTICLE_IMAGES = {
    'best-protein-powders.html':         TOPIC_IMAGES['protein'],
    'best-protein-shakes.html':          TOPIC_IMAGES['protein'],
    'best-protein-powder-for-women.html':TOPIC_IMAGES['protein'],
    'best-protein-powder-for-weight-loss.html': TOPIC_IMAGES['protein'],
    'best-whey-isolate.html':            TOPIC_IMAGES['protein'],
    'best-vegan-protein-powder.html':    TOPIC_IMAGES['protein'],
    'best-mass-gainer.html':             TOPIC_IMAGES['protein'],
    'best-bcaa.html':                    TOPIC_IMAGES['gym_general'],
    'best-bcaa-supplements.html':        TOPIC_IMAGES['gym_general'],
    'best-creatine.html':                TOPIC_IMAGES['creatine'],
    'best-creatine-for-women.html':      TOPIC_IMAGES['creatine'],
    'best-pre-workout.html':             TOPIC_IMAGES['preworkout'],
    'best-pre-workout-for-women.html':   TOPIC_IMAGES['preworkout'],
    'best-multivitamins.html':           TOPIC_IMAGES['multivit'],
    'best-multivitamins-for-men.html':   TOPIC_IMAGES['multivit'],
    'best-multivitamins-for-women.html': TOPIC_IMAGES['multivit'],
    'best-omega-3.html':                 TOPIC_IMAGES['omega3'],
    'best-vitamin-d-supplements.html':   TOPIC_IMAGES['vitd'],
    'best-vitamin-c-supplements.html':   TOPIC_IMAGES['health'],
    'best-vitamin-b-complex.html':       TOPIC_IMAGES['health'],
    'best-b12-supplements.html':         TOPIC_IMAGES['health'],
    'best-magnesium-supplements.html':   TOPIC_IMAGES['magnesium'],
    'best-zinc-supplements.html':        TOPIC_IMAGES['health'],
    'best-iron-supplements.html':        TOPIC_IMAGES['health'],
    'best-probiotics.html':              TOPIC_IMAGES['probiotics'],
    'best-digestive-enzymes.html':       TOPIC_IMAGES['probiotics'],
    'best-collagen-supplements.html':    TOPIC_IMAGES['collagen'],
    'best-collagen-powder.html':         TOPIC_IMAGES['collagen'],
    'best-hair-supplements.html':        TOPIC_IMAGES['collagen'],
    'best-ashwagandha.html':             TOPIC_IMAGES['ashwagandha'],
    'best-adaptogens.html':              TOPIC_IMAGES['ashwagandha'],
    'best-nootropics.html':              TOPIC_IMAGES['nootropics'],
    'best-greens-powders.html':          TOPIC_IMAGES['greens'],
    'best-sleep-supplements.html':       TOPIC_IMAGES['sleep'],
    'best-natural-sleep-aids.html':      TOPIC_IMAGES['sleep'],
    'best-melatonin-supplements.html':   TOPIC_IMAGES['sleep'],
    'best-sleep-trackers.html':          TOPIC_IMAGES['sleep'],
    'best-yoga-mats.html':               TOPIC_IMAGES['yoga'],
    'best-yoga-blocks.html':             TOPIC_IMAGES['yoga'],
    'best-dumbbells.html':               TOPIC_IMAGES['dumbbells'],
    'best-adjustable-dumbbells.html':    TOPIC_IMAGES['dumbbells'],
    'best-kettlebells.html':             TOPIC_IMAGES['kettlebell'],
    'best-resistance-bands.html':        TOPIC_IMAGES['resistance'],
    'best-pull-up-assistance-bands.html':TOPIC_IMAGES['resistance'],
    'best-treadmills-for-home.html':     TOPIC_IMAGES['treadmill'],
    'best-treadmill-mat.html':           TOPIC_IMAGES['treadmill'],
    'best-stationary-bikes.html':        TOPIC_IMAGES['treadmill'],
    'best-rowing-machines.html':         TOPIC_IMAGES['rowing'],
    'best-pull-up-bar.html':             TOPIC_IMAGES['pullup'],
    'best-pull-up-bar-door.html':        TOPIC_IMAGES['pullup'],
    'best-squat-rack.html':              TOPIC_IMAGES['squat'],
    'best-bench-press.html':             TOPIC_IMAGES['bench'],
    'best-barbell.html':                 TOPIC_IMAGES['bench'],
    'best-weight-plates.html':           TOPIC_IMAGES['bench'],
    'best-massage-guns.html':            TOPIC_IMAGES['massage'],
    'best-foam-roller.html':             TOPIC_IMAGES['foam'],
    'best-running-shoes.html':           TOPIC_IMAGES['running'],
    'best-fitness-trackers.html':        TOPIC_IMAGES['tracker'],
    'best-home-gym.html':                TOPIC_IMAGES['homegym'],
    'best-home-gym-under-500.html':      TOPIC_IMAGES['homegym'],
    'best-home-gym-cable-machine.html':  TOPIC_IMAGES['homegym'],
    'best-fat-burners-for-men.html':     TOPIC_IMAGES['gym_general'],
    'best-fat-burners-for-women.html':   TOPIC_IMAGES['gym_general'],
    'best-womens-fat-burners.html':      TOPIC_IMAGES['gym_general'],
    'best-weight-loss-supplements.html': TOPIC_IMAGES['gym_general'],
    'best-keto-supplements.html':        TOPIC_IMAGES['health'],
    'best-joint-supplements.html':       TOPIC_IMAGES['health'],
    'best-turmeric-supplements.html':    TOPIC_IMAGES['health'],
    'best-anti-aging-supplements.html':  TOPIC_IMAGES['collagen'],
    'best-electrolyte-supplements.html': TOPIC_IMAGES['gym_general'],
    'best-recovery-drinks.html':         TOPIC_IMAGES['gym_general'],
    'best-glutamine-supplements.html':   TOPIC_IMAGES['gym_general'],
    'best-l-carnitine-supplements.html': TOPIC_IMAGES['gym_general'],
    'best-dhea-supplements.html':        TOPIC_IMAGES['health'],
    'best-hormone-balance-supplements.html': TOPIC_IMAGES['health'],
    'best-prenatal-vitamins.html':       TOPIC_IMAGES['health'],
    'best-glucose-monitors.html':        TOPIC_IMAGES['health'],
    'best-blood-pressure-monitors.html': TOPIC_IMAGES['health'],
    'best-pulse-oximeters.html':         TOPIC_IMAGES['health'],
    'best-smart-scale.html':             TOPIC_IMAGES['tracker'],
    'best-fitness-apps-2026.html':       TOPIC_IMAGES['tracker'],
    'best-heart-rate-monitors.html':     TOPIC_IMAGES['tracker'],
    'best-smartwatches-for-fitness.html':TOPIC_IMAGES['tracker'],
    'best-oxygen-meters.html':           TOPIC_IMAGES['health'],
    'best-gym-bags.html':                TOPIC_IMAGES['gym_general'],
    'best-gym-gloves.html':              TOPIC_IMAGES['gym_general'],
    'best-gym-flooring.html':            TOPIC_IMAGES['homegym'],
    'best-gym-mirror.html':              TOPIC_IMAGES['homegym'],
    'best-weight-lifting-belts.html':    TOPIC_IMAGES['squat'],
    'best-chalk-for-lifting.html':       TOPIC_IMAGES['squat'],
    'best-compression-gear.html':        TOPIC_IMAGES['running'],
    'best-posture-correctors.html':      TOPIC_IMAGES['health'],
    'best-ergonomic-chairs.html':        TOPIC_IMAGES['health'],
    'best-standing-desks.html':          TOPIC_IMAGES['health'],
    'best-sports-water-bottles.html':    TOPIC_IMAGES['gym_general'],
    'best-protein-bars.html':            TOPIC_IMAGES['protein'],
    'best-blenders-for-protein-shakes.html': TOPIC_IMAGES['protein'],
    'best-calorie-counter-apps.html':    TOPIC_IMAGES['tracker'],
    'best-intermittent-fasting-supplements.html': TOPIC_IMAGES['health'],
    'best-metabolism-boosters.html':     TOPIC_IMAGES['gym_general'],
    'best-appetite-suppressants.html':   TOPIC_IMAGES['health'],
    'best-carb-blockers.html':           TOPIC_IMAGES['health'],
    'best-cbd-products.html':            TOPIC_IMAGES['health'],
    'best-eye-supplements.html':         TOPIC_IMAGES['health'],
    'best-liver-supplements.html':       TOPIC_IMAGES['health'],
    'best-supplement-stacks-for-recovery.html': TOPIC_IMAGES['gym_general'],
    'best-supplements-for-anxiety.html': TOPIC_IMAGES['ashwagandha'],
    'best-supplements-for-muscle-gain.html': TOPIC_IMAGES['creatine'],
    'best-supplements-for-runners.html': TOPIC_IMAGES['running'],
    'best-supplements-for-seniors.html': TOPIC_IMAGES['health'],
    'best-stretching-mobility-tools.html': TOPIC_IMAGES['foam'],
    'best-agility-ladder.html':          TOPIC_IMAGES['running'],
    'best-jump-rope.html':               TOPIC_IMAGES['gym_general'],
    'best-battle-ropes.html':            TOPIC_IMAGES['gym_general'],
    'best-speed-bag.html':               TOPIC_IMAGES['gym_general'],
    'best-trx-suspension-trainer.html':  TOPIC_IMAGES['gym_general'],
    'best-ab-rollers.html':              TOPIC_IMAGES['gym_general'],
    'best-plyo-box.html':                TOPIC_IMAGES['gym_general'],
    'best-medicine-ball.html':           TOPIC_IMAGES['gym_general'],
    'best-parallette-bars.html':         TOPIC_IMAGES['gym_general'],
    'best-balance-board.html':           TOPIC_IMAGES['yoga'],
    'best-hand-grippers.html':           TOPIC_IMAGES['gym_general'],
    'best-leg-press-machine.html':       TOPIC_IMAGES['squat'],
    'best-cable-crossover-machine.html': TOPIC_IMAGES['homegym'],
    'best-smith-machine.html':           TOPIC_IMAGES['homegym'],
    'best-power-rack-attachments.html':  TOPIC_IMAGES['squat'],
    'best-caffeine-l-theanine.html':     TOPIC_IMAGES['nootropics'],
    'best-recovery-drinks.html':         TOPIC_IMAGES['gym_general'],
    'best-natural-sleep-aids.html':      TOPIC_IMAGES['sleep'],
}

def gh_get(path):
    url = f'https://api.github.com/repos/{REPO}/contents/{path}'
    req = urllib.request.Request(url, headers={
        'Authorization': f'token {TOKEN}',
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'vitalpicks-bot'
    })
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

def gh_put(path, content, sha, msg):
    url = f'https://api.github.com/repos/{REPO}/contents/{path}'
    data = json.dumps({
        'message': msg,
        'content': base64.b64encode(content.encode()).decode(),
        'sha': sha
    }).encode()
    req = urllib.request.Request(url, data=data, method='PUT', headers={
        'Authorization': f'token {TOKEN}',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'vitalpicks-bot'
    })
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

print("Script loaded OK")
print(f"Total article image mappings: {len(ARTICLE_IMAGES)}")
